### ISSUE TITLE
Add button not aligned with the input field

### ISSUE THREAD

**Issue by TheSh4h** [TheSh4h/TODO-APP#2]

**Comment by TheSh4h** [comment]
relevant code will be situated in TodoInput.js file

**Comment by Aryan123-rgb** [comment]
@TheSh4h Would like to work on this.

**Comment by Aryan123-rgb** [comment]
@TheSh4h 
![Screenshot from 2023-06-03 11-43-16](https://github.com/TheSh4h/TODO-APP/assets/118872531/17094e5f-67a2-48ee-86da-081c5c141c84)

**Comment by Aryan123-rgb** [comment]
@TheSh4h  [issue-2](https://github.com/TheSh4h/TODO-APP/pull/3)
